name: linting
on: [push, pull_request]
jobs:
  pyflakes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lgeiger/pyflakes-action@master
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jpetrucciani/mypy-check@master
        with:
          mypy_flags: '--exclude examples --exclude setup'
